kind: Service
apiVersion: v1
metadata:
  name: daprdemo
  labels:
    app: daprdemo
spec:
  selector:
    app: daprdemo
  ports:
    - port: 80
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: daprdemo
  labels:
    app: daprdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daprdemo
  template:
    metadata:
      labels:
        app: daprdemo
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "daprdemo"
        dapr.io/app-port: "80"
    spec:
      containers:
      - name: daprdemo
        image: crgarakspublicacr.azurecr.io/daprdemo:1.0.12
        ports:
        - containerPort: 80