apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: crgar-aks-public-redis.redis.cache.windows.net:6380
  - name: redisPassword
    value: "fLGvpzGNFsNaVKX4vJhqbXFp7xBR5VCsmAzCaGB1hxg="
  - name: enableTLS
    value: true 