kind: Service
apiVersion: v1
metadata:
  name: client
  labels:
    app: client
spec:
  selector:
    app: client
  ports:
    - port: 80
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "client"
        dapr.io/app-port: "80"
    spec:
      containers:
      - name: client
        image: crgarakspublicacr.azurecr.io/client:1.0.10
        ports:
        - containerPort: 80
        imagePullPolicy: Always