kind: Service
apiVersion: v1
metadata:
  name: daprclient
  labels:
    app: daprclient
spec:
  selector:
    app: daprclient
  ports:
    - port: 80
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: daprclient
  labels:
    app: daprclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daprclient
  template:
    metadata:
      labels:
        app: daprclient
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "daprclient"
        dapr.io/app-port: "80"
    spec:
      containers:
      - name: daprclient
        image: crgarakspublicacr.azurecr.io/daprclient:1.0.10
        ports:
        - containerPort: 80
        imagePullPolicy: Always