kind: Service
apiVersion: v1
metadata:
  name: client
  labels:
    app: client
spec:
  selector:
    app: client
  ports:
    - port: 80
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: crgarakspublicacr.azurecr.io/client:1.0.12
        ports:
        - containerPort: 80